import React from 'react';

export interface Professional {
  id: string;
  name: string;
  photo: string;
  category: string;
  subcategory: string;
  location: string;
  bio: string;
  experience: string;
  rating: number;
  reviewCount: number;
  priceRange: string;
  phone: string;
  availability: string;
  services: { name: string; price: string }[];
  reviews: { client: string; rating: number; comment: string; date: string }[];
  gallery: string[];
  featured: boolean;
}

const REVIEWS_POOL = [
  { client: 'Maria G.', rating: 5, comment: 'Excelente profesional, muy recomendable. Llego a horario y el trabajo quedo impecable.', date: '2026-05-20' },
  { client: 'Jose L.', rating: 5, comment: 'Muy conforme con el resultado. Precio justo y muy buen trato.', date: '2026-06-01' },
  { client: 'Ana R.', rating: 4, comment: 'Buen trabajo, volveria a contratar. Puntual y responsable.', date: '2026-04-15' },
  { client: 'Carlos M.', rating: 5, comment: 'Lo recomiendo 100%. Resolvio el problema rapidamente.', date: '2026-06-10' },
  { client: 'Laura D.', rating: 4, comment: 'Muy profesional. Me explico todo antes de hacer el trabajo.', date: '2026-03-22' },
  { client: 'Pedro S.', rating: 5, comment: 'Un lujo tener a alguien asi cerca. Trabajo de primera.', date: '2026-06-18' },
  { client: 'Sofia P.', rating: 4, comment: 'Buen servicio, cumple con lo prometido.', date: '2026-05-05' },
  { client: 'Diego F.', rating: 5, comment: 'Lo llame por una urgencia y vino al toque. Muy agradecido.', date: '2026-06-22' },
];

const pickReviews = (count: number) => {
  const shuffled = [...REVIEWS_POOL].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};

export const PROFESSIONALS: Professional[] = [
  {
    id: 'carlos-perez',
    name: 'Carlos Perez',
    photo: '',
    category: 'Construccion',
    subcategory: 'Albañil',
    location: 'Chascomus Centro',
    bio: 'Albañil con 20 años de experiencia en construccion y remodelacion. Especialista en revoques, contrapisos, colocacion de ceramicos y ampliaciones. Trabajo con dedicacion y limpieza.',
    experience: '20 años',
    rating: 4.8,
    reviewCount: 15,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados',
    services: [
      { name: 'Revoque fino x m2', price: '$8,000' },
      { name: 'Colocacion ceramico x m2', price: '$12,000' },
      { name: 'Contrapiso x m2', price: '$6,000' },
      { name: 'Ampliacion menor (presupuesto)', price: 'a convenir' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: true,
  },
  {
    id: 'martina-lopez',
    name: 'Martina Lopez',
    photo: '',
    category: 'Profesionales',
    subcategory: 'Abogada',
    location: 'Chascomus',
    bio: 'Abogada especializada en derecho civil, familial y laboral. Asesoramiento juridico integral, redaccion de contratos, sucesiones y divorcios. Atencion personalizada.',
    experience: '12 años',
    rating: 4.9,
    reviewCount: 23,
    priceRange: '$$$',
    phone: '5492241567142',
    availability: 'Lunes a viernes 9-18',
    services: [
      { name: 'Consulta juridica', price: '$15,000' },
      { name: 'Redaccion de contrato', price: '$25,000' },
      { name: 'Sucesiones', price: 'a convenir' },
      { name: 'Divorcio express', price: '$80,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: true,
  },
  {
    id: 'juan-ramirez',
    name: 'Juan Ramirez',
    photo: '',
    category: 'Construccion',
    subcategory: 'Electricista',
    location: 'Chascomus Sur',
    bio: 'Electricista matriculado. Hago instalaciones, reparaciones, termicas, cables, bocas de luz, y puesta a tierra. Domicilios y comercios. Urgencias 24hs.',
    experience: '15 años',
    rating: 4.7,
    reviewCount: 31,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados + urgencias',
    services: [
      { name: 'Reparacion menor', price: '$10,000' },
      { name: 'Instalacion completa x punto', price: '$8,000' },
      { name: 'Termica y disyuntor', price: '$25,000' },
      { name: 'Puesta a tierra', price: '$35,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'sofia-mendoza',
    name: 'Sofia Mendoza',
    photo: '',
    category: 'Salud',
    subcategory: 'Veterinaria',
    location: 'Chascomus Centro',
    bio: 'Veterinaria especializada en pequenos animales. Consultas, vacunacion, castraciones, cirugias menores y emergencias. Atencion domiciliaria para mascotas que no pueden viajar.',
    experience: '8 años',
    rating: 4.9,
    reviewCount: 42,
    priceRange: '$$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados 10-20',
    services: [
      { name: 'Consulta general', price: '$12,000' },
      { name: 'Vacunacion antirrabica', price: '$5,000' },
      { name: 'Castracion felina', price: '$45,000' },
      { name: 'Visita domiciliaria', price: '$18,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: true,
  },
  {
    id: 'gaston-riera',
    name: 'Gaston Riera',
    photo: '',
    category: 'Construccion',
    subcategory: 'Plomero',
    location: 'Chascomus',
    bio: 'Plomero con 18 años de oficio. Reparacion de perdidas, instalacion de termotanques, cañerias, tanques de agua y destapaciones. Sin suciedad, trabajo limpio y garantizado.',
    experience: '18 años',
    rating: 4.6,
    reviewCount: 28,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados',
    services: [
      { name: 'Destapacion x artefacto', price: '$12,000' },
      { name: 'Reparacion de perdida', price: '$15,000' },
      { name: 'Instalacion termotanque', price: '$40,000' },
      { name: 'Colocacion baño completo', price: 'a convenir' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'lucia-torres',
    name: 'Lucia Torres',
    photo: '',
    category: 'Tecnologia',
    subcategory: 'Desarrolladora Web',
    location: 'Chascomus (remoto)',
    bio: 'Desarrolladora web full-stack. Creo sitios modernos, tiendas online, sistemas a medida y automatizaciones. Tecnologias: React, Next.js, Node.js, bases de datos.',
    experience: '6 años',
    rating: 5.0,
    reviewCount: 19,
    priceRange: '$$$',
    phone: '5492241567142',
    availability: 'Lunes a viernes 10-19',
    services: [
      { name: 'Landing page', price: 'desde $150,000' },
      { name: 'Sitio web completo', price: 'desde $300,000' },
      { name: 'Tienda online', price: 'desde $500,000' },
      { name: 'Sistema a medida', price: 'a convenir' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: true,
  },
  {
    id: 'roberto-gimenez',
    name: 'Roberto Gimenez',
    photo: '',
    category: 'Construccion',
    subcategory: 'Pintor',
    location: 'Chascomus Norte',
    bio: 'Pintor de interiores y exteriores. Preparacion de superficies, pintura latex, esmaltes, revestimientos, texturados y papel tapiz. Presupuesto sin cargo.',
    experience: '14 años',
    rating: 4.5,
    reviewCount: 22,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados 8-18',
    services: [
      { name: 'Pintura interior x ambiente', price: '$45,000' },
      { name: 'Pintura exterior x m2', price: '$7,000' },
      { name: 'Texturado x m2', price: '$10,000' },
      { name: 'Presupuesto completo', price: 'sin cargo' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'diego-martinez',
    name: 'Diego Martinez',
    photo: '',
    category: 'Hogar',
    subcategory: 'Jardinero',
    location: 'Chascomus',
    bio: 'Jardinero y paisajista. Diseno y mantenimiento de jardines, poda, corte de cesped, plantacion y sistemas de riego. Transformo tu patio en un espacio unico.',
    experience: '10 años',
    rating: 4.7,
    reviewCount: 16,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Martes a sabados 8-17',
    services: [
      { name: 'Corte de cesped', price: '$15,000' },
      { name: 'Poda de arbol', price: 'desde $25,000' },
      { name: 'Diseno de jardin', price: 'a convenir' },
      { name: 'Mantenimiento mensual', price: '$40,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'maria-fernandez',
    name: 'Maria Fernandez',
    photo: '',
    category: 'Profesionales',
    subcategory: 'Contadora',
    location: 'Chascomus Centro',
    bio: 'Contadora publica nacional. Liquidacion de impuestos (IVA, Ganancias, Monotributo), sueldos, balances y asesoramiento impositivo para particulares y PyMEs.',
    experience: '16 años',
    rating: 4.8,
    reviewCount: 35,
    priceRange: '$$$',
    phone: '5492241567142',
    availability: 'Lunes a viernes 9-17',
    services: [
      { name: 'Liquidacion mensual monotributo', price: '$8,000' },
      { name: 'Liquidacion IVA mensual', price: '$18,000' },
      { name: 'Sueldos (por empleado)', price: '$12,000' },
      { name: 'Balance anual', price: 'a convenir' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'pablo-aguirre',
    name: 'Pablo Aguirre',
    photo: '',
    category: 'Construccion',
    subcategory: 'Gasista',
    location: 'Chascomus',
    bio: 'Gasista matriculado. Instalacion y reparacion de artefactos a gas, calefones, termotanques, cocinas y calefaccion. Revision de instalaciones y certificaciones.',
    experience: '22 años',
    rating: 4.9,
    reviewCount: 40,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados 8-20',
    services: [
      { name: 'Reparacion de artefacto', price: '$12,000' },
      { name: 'Instalacion de calefon', price: '$35,000' },
      { name: 'Certificacion completa', price: '$25,000' },
      { name: 'Colocacion de cocina', price: '$15,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: true,
  },
  {
    id: 'valentina-ruiz',
    name: 'Valentina Ruiz',
    photo: '',
    category: 'Tecnologia',
    subcategory: 'Fotografa',
    location: 'Chascomus',
    bio: 'Fotografa profesional especializada en retratos, eventos, productos y sesiones de fotografia para redes. Edicion digital y entregas en 48hs.',
    experience: '7 años',
    rating: 4.6,
    reviewCount: 27,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a domingos (con cita)',
    services: [
      { name: 'Sesion de retratos', price: '$35,000' },
      { name: 'Cobertura de evento', price: 'desde $80,000' },
      { name: 'Fotografia de producto', price: '$20,000' },
      { name: 'Book de redes', price: '$50,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'horacio-molina',
    name: 'Horacio Molina',
    photo: '',
    category: 'Construccion',
    subcategory: 'Cerrajero',
    location: 'Chascomus 24hs',
    bio: 'Cerrajero con servicio de urgencia 24hs. Apertura de puertas, cambio de cerraduras, instalacion de rejas, copia de llaves y sistemas de seguridad.',
    experience: '12 años',
    rating: 4.4,
    reviewCount: 33,
    priceRange: '$$',
    phone: '5492241567142',
    availability: '24 horas, todos los dias',
    services: [
      { name: 'Apertura de puerta (urgencia)', price: '$15,000' },
      { name: 'Cambio de cerradura', price: '$25,000' },
      { name: 'Instalacion de reja', price: 'desde $40,000' },
      { name: 'Copia de llave', price: '$3,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'carla-dominguez',
    name: 'Carla Dominguez',
    photo: '',
    category: 'Educacion',
    subcategory: 'Profesora Particular',
    location: 'Chascomus / Online',
    bio: 'Profesora de nivel secundario y terciario. Apoyo escolar en matematica, fisica, quimica e ingles. Preparacion para examenes e ingresos. Clases presenciales y online.',
    experience: '9 años',
    rating: 4.8,
    reviewCount: 38,
    priceRange: '$',
    phone: '5492241567142',
    availability: 'Lunes a viernes 14-21',
    services: [
      { name: 'Clase individual presencial', price: '$8,000' },
      { name: 'Clase individual online', price: '$5,000' },
      { name: 'Prep. examen mensual', price: '$25,000' },
      { name: 'Apoyo semanal (4 clases)', price: '$28,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'facundo-peralta',
    name: 'Facundo Peralta',
    photo: '',
    category: 'Hogar',
    subcategory: 'Mecañico a domicilio',
    location: 'Chascomus y zona',
    bio: 'Mecañico automotriz a domicilio. Diagnostico computarizado, cambios de aceite, frenos, suspension, electricidad del auto y puesta a punto. Voy a tu casa o trabajo.',
    experience: '13 años',
    rating: 4.7,
    reviewCount: 29,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a sabados 9-19',
    services: [
      { name: 'Cambio de aceite y filtro', price: '$25,000' },
      { name: 'Diagnostico computarizado', price: '$12,000' },
      { name: 'Cambio de pastillas de freno', price: '$35,000' },
      { name: 'Puesta a punto general', price: 'a convenir' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'romina-insua',
    name: 'Romina Insua',
    photo: '',
    category: 'Salud',
    subcategory: 'Nutricionista',
    location: 'Chascomus / Online',
    bio: 'Licenciada en Nutricion. Planes alimentarios personalizados para descenso de peso, rendimiento deportivo, patologias digestivas y reeducacion alimentaria.',
    experience: '6 años',
    rating: 4.9,
    reviewCount: 45,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a viernes 9-20',
    services: [
      { name: 'Consulta inicial + plan', price: '$20,000' },
      { name: 'Control de seguimiento', price: '$10,000' },
      { name: 'Plan deportivo', price: '$25,000' },
      { name: 'Asesoria online', price: '$15,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'tomas-silva',
    name: 'Tomas Silva',
    photo: '',
    category: 'Transporte',
    subcategory: 'Fletes y Mudanzas',
    location: 'Chascomus',
    bio: 'Servicio de fletes y mudanzas. Camion con capacidad para 2 ambientes. Carga y descarga incluida. Presupuesto sin cargo. Atencion responsable y cuidadosa.',
    experience: '8 años',
    rating: 4.5,
    reviewCount: 20,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a domingos',
    services: [
      { name: 'Flete local (dentro de Chascomus)', price: '$30,000' },
      { name: 'Flete interurbano', price: 'a convenir' },
      { name: 'Mudanza 2 ambientes', price: '$80,000' },
      { name: 'Carga de escombros', price: '$25,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'andrea-mansilla',
    name: 'Andrea Mansilla',
    photo: '',
    category: 'Belleza',
    subcategory: 'Manicurista a domicilio',
    location: 'Chascomus',
    bio: 'Manicurista profesional con experiencia en esculpidas, semipermanentes, kapping, disenos artisticos y cuidado de uñas. Voy a tu domicilio con todo el material.',
    experience: '5 años',
    rating: 4.8,
    reviewCount: 34,
    priceRange: '$',
    phone: '5492241567142',
    availability: 'Lunes a sabados 10-19',
    services: [
      { name: 'Esmaltado semipermanente', price: '$12,000' },
      { name: 'Esculpidas en gel (juego)', price: '$35,000' },
      { name: 'Kapping', price: '$25,000' },
      { name: 'Diseno artistico c/u', price: '$3,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'ivan-moreno',
    name: 'Ivan Moreno',
    photo: '',
    category: 'Tecnologia',
    subcategory: 'Tecnico de PC',
    location: 'Chascomus',
    bio: 'Tecnico en reparacion de PC y notebooks. Diagnostico, reparacion de software, cambio de componentes, armado a medida y recuperacion de datos.',
    experience: '11 años',
    rating: 4.6,
    reviewCount: 25,
    priceRange: '$$',
    phone: '5492241567142',
    availability: 'Lunes a viernes 9-18, sabados 9-13',
    services: [
      { name: 'Diagnostico', price: '$5,000' },
      { name: 'Formateo y optimizacion', price: '$15,000' },
      { name: 'Cambio de componentes', price: '$8,000 + repuesto' },
      { name: 'Armado de PC', price: 'a convenir' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
  {
    id: 'elena-vazquez',
    name: 'Elena Vazquez',
    photo: '',
    category: 'Hogar',
    subcategory: 'Servicio de limpieza',
    location: 'Chascomus Centro',
    bio: 'Servicio de limpieza integral para hogares y oficinas. Limpieza general, vidrios, cocinas, baños y post-obra. Productos e insumos incluidos. Resultado garantizado.',
    experience: '7 años',
    rating: 4.7,
    reviewCount: 18,
    priceRange: '$',
    phone: '5492241567142',
    availability: 'Lunes a sabados 8-16',
    services: [
      { name: 'Limpieza general hogar (xhora)', price: '$5,000' },
      { name: 'Limpieza de oficina', price: 'a convenir' },
      { name: 'Limpieza post-obra x m2', price: '$3,000' },
      { name: 'Lavado de vidrios (xhora)', price: '$6,000' },
    ],
    reviews: pickReviews(3),
    gallery: [],
    featured: false,
  },
];

export const CATEGORIES = [
  { id: 'Construccion', icon: 'construccion', count: 6 },
  { id: 'Profesionales', icon: 'profesionales', count: 2 },
  { id: 'Tecnologia', icon: 'tecnologia', count: 3 },
  { id: 'Salud', icon: 'salud', count: 2 },
  { id: 'Educacion', icon: 'educacion', count: 1 },
  { id: 'Hogar', icon: 'hogar', count: 3 },
  { id: 'Transporte', icon: 'transporte', count: 1 },
  { id: 'Belleza', icon: 'belleza', count: 1 },
];

export const SUBCATEGORIES_BY_CATEGORY: Record<string, string[]> = {
  Construccion: ['Albañil', 'Electricista', 'Plomero', 'Pintor', 'Gasista', 'Cerrajero'],
  Profesionales: ['Abogada', 'Contadora'],
  Tecnologia: ['Desarrolladora Web', 'Fotografa', 'Tecnico de PC'],
  Salud: ['Veterinaria', 'Nutricionista'],
  Educacion: ['Profesora Particular'],
  Hogar: ['Jardinero', 'Mecañico a domicilio', 'Servicio de limpieza'],
  Transporte: ['Fletes y Mudanzas'],
  Belleza: ['Manicurista a domicilio'],
};

export const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  construccion: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="6" width="20" height="12" rx="2"/><path d="M12 6v12"/><path d="M7 6V4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2"/><path d="M2 10h20"/></svg>,
  profesionales: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>,
  tecnologia: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>,
  salud: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>,
  educacion: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c6 3 12 3 12 0v-5"/></svg>,
  hogar: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>,
  transporte: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>,
  belleza: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a4 4 0 0 1 4 4v2a4 4 0 0 1-8 0V6a4 4 0 0 1 4-4z"/><path d="M20 22v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/></svg>,
};

export function getProfessionalsByCategory(cat: string) {
  return PROFESSIONALS.filter((p) => p.category === cat);
}

export function findProfessionalById(id: string) {
  return PROFESSIONALS.find((p) => p.id === id);
}
